/** Enums */
import { UserProfilePictureEnum } from 'acad-game-lib';

/** Assets */
import {
  DefaultProfilePic,
  GenericManOne,
  GenericManTwo,
  GenericManThree,
  GenericManFour,
  GenericManFive,
  GenericWomanOne,
  GenericWomanTwo,
  GenericWomanThree,
  GenericWomanFour,
  GenericWomanFive,
  SportAmericanFootball,
  SportBasketball,
  SportBicycle,
  SportFight,
  SportFootball,
  SportHandball,
  SportRun,
  SportSurf,
  SportSwimming,
  SportTennis,
  FunnyIHateLegDay,
  FunnyBodyBuilder,
  SpecialAssassinsScreed,
  SpecialBuzz,
  SpecialCS,
  SpecialGTA,
  SpecialGodOfWar,
  SpecialGoku,
  SpecialMario,
  SpecialSpike,
  SpecialTheSims,
  SpecialZelda,
} from '../assets/images/profilePics';

/**
 * Mapping between User Get profile picture enum and profile picture file.
 */
export const userGetProfilePictureImageMap = new Map<
  UserProfilePictureEnum,
  string
>([
  [UserProfilePictureEnum.DEFAULT, DefaultProfilePic],
  [UserProfilePictureEnum.GENERIC_MAN_ONE, GenericManOne],
  [UserProfilePictureEnum.GENERIC_MAN_TWO, GenericManTwo],
  [UserProfilePictureEnum.GENERIC_MAN_THREE, GenericManThree],
  [UserProfilePictureEnum.GENERIC_MAN_FOUR, GenericManFour],
  [UserProfilePictureEnum.GENERIC_MAN_FIVE, GenericManFive],
  [UserProfilePictureEnum.GENERIC_WOMAN_ONE, GenericWomanOne],
  [UserProfilePictureEnum.GENERIC_WOMAN_TWO, GenericWomanTwo],
  [UserProfilePictureEnum.GENERIC_WOMAN_THREE, GenericWomanThree],
  [UserProfilePictureEnum.GENERIC_WOMAN_FOUR, GenericWomanFour],
  [UserProfilePictureEnum.GENERIC_WOMAN_FIVE, GenericWomanFive],
  [UserProfilePictureEnum.SPORT_AMERICAN_FOOTBALL, SportAmericanFootball],
  [UserProfilePictureEnum.SPORT_BASKETBALL, SportBasketball],
  [UserProfilePictureEnum.SPORT_BICYCLE, SportBicycle],
  [UserProfilePictureEnum.SPORT_FIGHT, SportFight],
  [UserProfilePictureEnum.SPORT_FOOTBALL, SportFootball],
  [UserProfilePictureEnum.SPORT_HANDBALL, SportHandball],
  [UserProfilePictureEnum.SPORT_RUN, SportRun],
  [UserProfilePictureEnum.SPORT_SURF, SportSurf],
  [UserProfilePictureEnum.SPORT_SWIMMING, SportSwimming],
  [UserProfilePictureEnum.SPORT_TENNIS, SportTennis],
  [UserProfilePictureEnum.FUNNY_I_HATE_LEG_DAY, FunnyIHateLegDay],
  [UserProfilePictureEnum.FUNNY_BODYBUILDER, FunnyBodyBuilder],
  [UserProfilePictureEnum.SPECIAL_ASSASSINS_SCREED, SpecialAssassinsScreed],
  [UserProfilePictureEnum.SPECIAL_BUZZ, SpecialBuzz],
  [UserProfilePictureEnum.SPECIAL_CS, SpecialCS],
  [UserProfilePictureEnum.SPECIAL_GOD_OF_WAR, SpecialGodOfWar],
  [UserProfilePictureEnum.SPECIAL_GOKU, SpecialGoku],
  [UserProfilePictureEnum.SPECIAL_GTA, SpecialGTA],
  [UserProfilePictureEnum.SPECIAL_MARIO, SpecialMario],
  [UserProfilePictureEnum.SPECIAL_SPIKE, SpecialSpike],
  [UserProfilePictureEnum.SPECIAL_THE_SIMS, SpecialTheSims],
  [UserProfilePictureEnum.SPECIAL_ZELDA, SpecialZelda],
]);
